### ISSUE TITLE
[epic] Table Schema Catalog 

### ISSUE THREAD

**Issue by lauragift21** [frictionlessdata/schema-catalog#3]
**Idea:** Creation of a new Frictionless Data product: Table Schema Catalog.

**Context** https://github.com/frictionlessdata/forum/issues/5

As an organization that brings simplicity and gracefulness to the messy world of data, we want table schemas to be easily found and usable, as well as gathered in one place and well presented, so that they become standards. 

## Job Stories and Analysis 

See https://docs.google.com/document/d/1DVu1tpg6lO_R7ZjrAlQXsQc12YU6-fOGg8KI1FiYEWc/edit#

## Design

Info architecture

```
/@myorg/abc
/@myorg/abc/v2.0
/@myorg/abc/tableschema.json
```

## Acceptance

* [ ] We have a new product - Table Schema Catalog
* [ ] schemas.frictionlessdata.io is up and running

Todo: Brainstorm possible job stories

## Tasks 

* [x] Ask @lwinfree to get schemas.frictionlessdata.io pointing at frictionlessdata.github.io so that when repo is ready with CNAME it will work straight away - @lauragift21 to ping @lwinfree / @amercader 
* [x] do a simple mockup @lauragift21 
  * [x] home page 
  * [x] list of table schemas
  * [x] table schema
* [x] stub the main pages of the website @monikappv
  * [x] really basic home page with project description
  * [x] list of table schemas page
  * [x] individual table schema page 
  * [x] about page
* [x] add some content to the about page @monikappv 
* [x] build the pipeline @monikappv https://github.com/frictionlessdata/project/issues/511
  * create a page for each (new) schema that gets added to the catalog.json 
  * Everyone should be able to edit the file → send PR 
  * Once PR gets approved, site is updated 
* [ ] make the search more advanced - a way to search on the website for a schema: full-text, filter/facets, using all the metadata/frontmatter

#### Johan  
* [ ] update README.md https://github.com/frictionlessdata/schema-catalog
* Product owner-ing ..
#### Monika + Gift
* [x] Get on a call to discuss further steps
* [x] Start stubbing the website

### Notes
* We will go for Vuepress
* https://github.com/frictionlessdata/schema-catalog catalog.csv containing table schemas
* Johan = Product Owner
* Build basic vuepress website and then iterate and improve search options (we want advanced filter search e.g. filter by country)
* Have a sync meeting once per week/two weeks 
---

### Home page

![home_tableschema](https://user-images.githubusercontent.com/56799741/82794207-c5cd8280-9e7a-11ea-830a-b21f82e468fb.png)

### Catalog page

![catalog_tableschema](https://user-images.githubusercontent.com/56799741/82794248-d41b9e80-9e7a-11ea-94e8-ac396ec0bdeb.png)

### Schema page

![schema_tableschema](https://user-images.githubusercontent.com/56799741/82794285-e39ae780-9e7a-11ea-91ae-1b599e75dab4.png)

https://xd.adobe.com/view/4a97d38c-eef2-4bcf-69cb-a4481ef98130-3ca6/
