### ISSUE TITLE
Table Schema Page Mockup

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/schema-catalog#5]
A mock-up suggestion for a table schema individual page.

## Acceptance

* [ ] a mock-up of a table schema page 
* [ ] signed off

## Tasks

* [x] do a mockup of the schema page based on https://docs.google.com/document/d/1DVu1tpg6lO_R7ZjrAlQXsQc12YU6-fOGg8KI1FiYEWc/edit#heading=h.ednryp72bfqo
* [x] come up with a suggestion for the table schema preview
* [x] ask for feedback
* [ ] improve
* [ ] polish off
* [ ] implement

---

## Mock-up

![table-schema-page-2](https://user-images.githubusercontent.com/56799741/83895419-55b4db80-a75b-11ea-947e-b440f16e8001.jpg)

*NB:* **Preview** could show up when clicking on the `schema` link ..
*NB2:* Might need to add a `create a file` compliant to the schema option

**Comment by monikappv** [comment]
@rufuspollock so this is how i roughly imagine a schema individual page.. as written under the mock-up in the issue description, people could **preview a table schema** when clicking on the schema link.. (?)

**Comment by monikappv** [comment]
@johanricher you can also have a look and let me know your thoughts..

**Comment by johanricher** [comment]
I like it! Thanks @monikappv 

I think the Field Information and Data Model blocks might be merged in some way.

So, basically, here's what it come down to. If you display the "data model" of the schema as a table, it could look like the "Modèle de données" part of the documentation page as built for schema.data.gouv ([example](https://schema.data.gouv.fr/scdl/adresses/latest/documentation.html)):

![image](https://user-images.githubusercontent.com/10212787/84170118-9a04ec00-aa79-11ea-9953-64c48e93a0e1.png)

Yeah, if the description of a a field is too long, it's pretty much unreadable. Might be better if the table is full-width, I don't know.

So then the other option is _not_ displaying the data model as a table, and it could look like this ([from this example](https://scdl.opendatafrance.net/docs/schemas/adresses.html) which uses [Table Schema to Markdown](https://www.npmjs.com/package/@opendataschema/table-schema-to-markdown)):

![image](https://user-images.githubusercontent.com/10212787/84170603-2f07e500-aa7a-11ea-811f-3cfecd8fcb0c.png)

I know not very sexy either. :wink: 

Also, I don't know what you mean by "previewing a table schema". You mean an example of a valid file following the schema? If so, then you have two options:
- If the schema has a value for the `resources` property then you could link to it, it's used exactly for that purpose ([documented here](https://specs.frictionlessdata.io/patterns/#specification-9))
- If no resources, then you can create fake one. [There's actually a tool for that!](https://gitlab.com/healthdatahub/tsfaker/) but that might not be what you have in mind, and not very useful for the user.
